[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200
lib_deps =
    gilmaimon/ArduinoWebsockets @ ^0.5.3
    bogde/HX711 @ ^0.7.5
    miguelbalboa/MFRC522 @ ^1.4.10
    bblanchon/ArduinoJson @ ^6.21.3
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.12.1
